name: big_float
description: BigFloat library to use basic arithmetic operations
version: 0.0.2
repository: https://github.com/gubnota/big_float

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
